### ISSUE TITLE
Observe inheritence

### ISSUE THREAD

**Issue by cliffhall** [HQ20/soldoc#48]
The current documentation only shows the members of the contracts themselves. Inherited functionality is an important part of the documentation picture.

**Comment by obernardovieira** [comment]
Hi, that's a really good point.
We are planning the new release with some great news. I will definitely put that one in. Thank you so much.

**Comment by obernardovieira** [comment]
Hi, I've included this in **soldoc@0.1.2-beta.6**. If you can, give some feedback. Thank you :+1:

**Comment by cliffhall** [comment]
@obernardovieira it would be great to see an inheritance example in the demo.

**Comment by obernardovieira** [comment]
https://soldoc-demo.netlify.com/erc20. On the right side, the IERC20 is listed.
Although, it needs some work. Because I've ignored IERC20 and now it redirects me to a page that does not exist.
PS. It's only working with HTML output.

**Comment by cliffhall** [comment]
Saw that. Thought it’d be nice within the scope of rendered contracts to see it

**Comment by obernardovieira** [comment]
You mean, below the name in the center of the page?

**Comment by cliffhall** [comment]
I mean it would be nice to have an example of a contract inheriting from another where both lived in the example.

**Comment by 7-of-9** [comment]
@obernardovieira - nice stuff; this tool is super fast and works really well.

One request: it doesn't seem to handle contracts that inherit from more than one base class or interface -- it just documents the first inherited contract in the output.

**Comment by obernardovieira** [comment]
Hi @7-of-9 
I appreciate your feedback.
It is most likely documenting only the first one. I'll confirm that and open an issue linked to this one in case I get the same result :+1:

Thank you so much.

**Comment by obernardovieira** [comment]
I do confirm the issue :+1: thank you so much once again :clap:
