### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by msacco22** [HQ20/soldoc#53]
* **Node Version**: v12.13.0
* **Soldoc Version**: v0.1.2-beta.0
* **Platform**: 16.04.1-Ubuntu x64

params: () => (val, render) => paramComments.get(render(val)),
TypeError: Cannot read property 'get' of undefined

I am getting this error when running soldoc on a particular contract. Strangely, it runs fine on contracts such as Ownable.sol (standard contract) and Migrations.sol (truffle suite).

After some manual debugging it seems to be related to the constructor having arguments. The constructor with arguments is throwing the error shown above.

**Comment by obernardovieira** [comment]
Hi,

I really appreciate your time opening this issue. We had a few problems with this method, although it's working just fine lately. If you can't share the contract, it's more difficult to help, but I understand.
In any case, we are planning to change it a bit and maybe remove that method. I'll keep you posted.
I hope that we get a new release by the end of next week (29th Nov.).

Thank you so much :pray:

**Comment by obernardovieira** [comment]
Hello,

This is already solved in #61 Will release a beta version between today and tomorrow.

Thanks again :pray:
